version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/HC-backend
    overwrite: yes

permissions:
  - object: /home/ubuntu/HC-backend
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu