permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: ChatGPT Code Review
        uses: anc95/ChatGPT-CodeReview@dev
        env:
          CR_GITHUB_TOKEN: ${{ secrets.CR_GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Korean
